name: Publish NPM Package
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - name: install npm packages
              run: npm install --legacy-peer-deps

            - name: publish npm package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
